id = "go-debug"
name = "Go Debug"
version = "0.0.1"
schema_version = 1
authors = ["RajaSunrise"]
description = "Enhanced Go debugging experience for Zed, inspired by GoLand."
repository = "https://github.com/RajaSunrise/zed-go-debug"

[debug_adapters.go-debug]
schema_path = "debug_adapter_schemas/go-debug.json"

[slash_commands.go-debug]
description = "Go Debug utilities"
tooltip_text = "Utilities for checking Go Debug environment"
requires_argument = true
